version: "3.8"

services:
  node:
    container_name: node
    image: node:18
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: sh -c "npm install --verbose && npm run watch"
